import { Button } from './Button'
import {
  buttonSizeProps,
  buttonVariantProps,
} from './buttonPropsConst'
import Icon from '../IconWrapper/Icon'

export const ButtonPlayround =
  ({
    size,
  }: {
    size: buttonSizeProps
  }) => {
    return (
      <>
        <div>
          <div>
            <Button className="bg-test-primary text-white">
              Primary
            </Button>
            <Button className="bg-test-secondary text-white">
              Secondary
            </Button>
            <Button className="bg-test-tertiary text-white">
              Tertiary
            </Button>
          </div>
          <div className="flex items-center gap-12">
            <span>
              {size}
            </span>
            <div className="flex flex-col gap-4 p-8">
              {/* Primary */}
              <span className="text-foreground-high">
                Primary
              </span>
              <Button
                size={size}
                className="col-span-3"
                leftIcon={
                  <Icon name="Plus" />
                }
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                disabled
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                loading
              />
            </div>

            {/* Outline */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-foreground-high">
                Outline
              </span>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                disabled
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                loading
              />
            </div>

            {/* Secondary */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-foreground-high">
                Secondary
              </span>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                disabled
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                loading
              />
            </div>

            {/* Ghost */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-foreground-high">
                Ghost
              </span>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                disabled
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                loading
              />
            </div>

            {/* destructive */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-foreground-high">
                destructive
              </span>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                disabled
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                loading
              />
            </div>
          </div>
        </div>
        <div className="bg-[#011934] w-fit">
          <div className="flex items-center gap-12">
            <span>
              {size}
            </span>
            <div className="flex flex-col gap-4 p-8">
              {/* Default */}
              <span className="text-inv-foreground-high">
                Default
              </span>
              <Button
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                disabled
                inverse
              >
                Button
              </Button>
              <Button
                size={size}
                className="col-span-3"
                loading
                inverse
              />
            </div>

            {/* outline */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-inv-foreground-high">
                outline
              </span>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                disabled
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.OUTLINE
                }
                size={size}
                className="col-span-3"
                loading
                inverse
              />
            </div>

            {/* Secondary */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-inv-foreground-high">
                Secondary
              </span>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                disabled
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.SECONDARY
                }
                size={size}
                className="col-span-3"
                loading
                inverse
              />
            </div>

            {/* Ghost */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-inv-foreground-high">
                Ghost
              </span>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                disabled
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.GHOST
                }
                size={size}
                className="col-span-3"
                loading
                inverse
              />
            </div>

            {/* destructive */}
            <div className="flex flex-col gap-4 p-8">
              <span className="text-inv-foreground-high">
                destructive
              </span>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                disabled
                inverse
              >
                Button
              </Button>
              <Button
                variant={
                  buttonVariantProps.DESTRUCTIVE
                }
                size={size}
                className="col-span-3"
                loading
                inverse
              />
            </div>
          </div>
        </div>
      </>
    )
  }
