import { Button } from './Button';
import type { Meta, StoryObj } from '@storybook/react-vite';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Playground: Story;
export declare const Sizes: Story;
export declare const Variants: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
export declare const Inverse: Story;
export declare const LeftIcon: Story;
export declare const RightIcon: Story;
