import {
  Tabs,
  TabsList,
} from './tab'
import { TabsTrigger } from './TabTrigger'
import { TabsContent } from './TabContent'
import {
  tabListSizeProps,
  tabListVariantProps,
  tabTriggerVariantProps,
} from './TabPropsConst'

export const TabPlayround =
  () => {
    return (
      <>
        {Object.values(
          tabListSizeProps,
        ).map((size) => (
          <>
            {Object.values(
              tabListVariantProps,
            ).map(
              (variant) => (
                <>
                  <h2 className="text-2xl font-bold">
                    {variant}{' '}
                    / {size}
                  </h2>
                  <Tabs
                    defaultValue="account"
                    className="w-full bg-accent"
                  >
                    <TabsList
                      variant={
                        variant
                      }
                      size={
                        size
                      }
                      inverse
                    >
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="1"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="2"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="3"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="4"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="5"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="6"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="7"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="8"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="9"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="10"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent value="1">
                      Content
                      1
                    </TabsContent>
                    <TabsContent value="2">
                      Content
                      2
                    </TabsContent>
                    <TabsContent value="3">
                      Content
                      3
                    </TabsContent>
                    <TabsContent value="4">
                      Content
                      4
                    </TabsContent>
                    <TabsContent value="5">
                      Content
                      5
                    </TabsContent>
                    <TabsContent value="6">
                      Content
                      6
                    </TabsContent>
                    <TabsContent value="7">
                      Content
                      7
                    </TabsContent>
                    <TabsContent value="8">
                      Content
                      8
                    </TabsContent>
                    <TabsContent value="9">
                      Content
                      9
                    </TabsContent>
                    <TabsContent value="10">
                      Content
                      10
                    </TabsContent>
                  </Tabs>

                  <h2 className="text-2xl font-bold">
                    {variant}{' '}
                    / {size}
                  </h2>
                  <Tabs
                    defaultValue="account"
                    className="w-full bg-accent"
                  >
                    <TabsList
                      variant={
                        variant
                      }
                      size={
                        size
                      }
                      inverse={
                        true
                      }
                    >
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="1"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="2"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="3"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="4"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="5"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="6"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="7"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="8"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="9"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="10"
                        inverse
                      >
                        Tab
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent value="1">
                      Content
                      1
                    </TabsContent>
                    <TabsContent value="2">
                      Content
                      2
                    </TabsContent>
                    <TabsContent value="3">
                      Content
                      3
                    </TabsContent>
                    <TabsContent value="4">
                      Content
                      4
                    </TabsContent>
                    <TabsContent value="5">
                      Content
                      5
                    </TabsContent>
                    <TabsContent value="6">
                      Content
                      6
                    </TabsContent>
                    <TabsContent value="7">
                      Content
                      7
                    </TabsContent>
                    <TabsContent value="8">
                      Content
                      8
                    </TabsContent>
                    <TabsContent value="9">
                      Content
                      9
                    </TabsContent>
                    <TabsContent value="10">
                      Content
                      10
                    </TabsContent>
                  </Tabs>

                  <h2 className="text-2xl font-bold">
                    {variant}{' '}
                    / {size}
                  </h2>
                  <Tabs
                    defaultValue="account"
                    className="w-full"
                  >
                    <TabsList
                      variant={
                        tabListVariantProps.OUTLINE
                      }
                      size={
                        size
                      }
                    >
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="1"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="2"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="3"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="4"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="5"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="6"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="7"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="8"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="9"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.FILL
                        }
                        value="10"
                      >
                        Tab
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent value="1">
                      Content
                      1
                    </TabsContent>
                    <TabsContent value="2">
                      Content
                      2
                    </TabsContent>
                    <TabsContent value="3">
                      Content
                      3
                    </TabsContent>
                    <TabsContent value="4">
                      Content
                      4
                    </TabsContent>
                    <TabsContent value="5">
                      Content
                      5
                    </TabsContent>
                    <TabsContent value="6">
                      Content
                      6
                    </TabsContent>
                    <TabsContent value="7">
                      Content
                      7
                    </TabsContent>
                    <TabsContent value="8">
                      Content
                      8
                    </TabsContent>
                    <TabsContent value="9">
                      Content
                      9
                    </TabsContent>
                    <TabsContent value="10">
                      Content
                      10
                    </TabsContent>
                  </Tabs>

                  <Tabs
                    defaultValue="account"
                    className="w-full"
                  >
                    <TabsList
                      variant={
                        tabListVariantProps.BOTTOM_BORDER
                      }
                      size={
                        size
                      }
                    >
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="1"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="2"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="3"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="4"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="5"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="6"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="7"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="8"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="9"
                      >
                        Tab
                      </TabsTrigger>
                      <TabsTrigger
                        size={
                          size
                        }
                        variant={
                          tabTriggerVariantProps.OUTLINE
                        }
                        value="10"
                      >
                        Tab
                      </TabsTrigger>
                    </TabsList>
                    <TabsContent value="1">
                      Content
                      1
                    </TabsContent>
                    <TabsContent value="2">
                      Content
                      2
                    </TabsContent>
                    <TabsContent value="3">
                      Content
                      3
                    </TabsContent>
                    <TabsContent value="4">
                      Content
                      4
                    </TabsContent>
                    <TabsContent value="5">
                      Content
                      5
                    </TabsContent>
                    <TabsContent value="6">
                      Content
                      6
                    </TabsContent>
                    <TabsContent value="7">
                      Content
                      7
                    </TabsContent>
                    <TabsContent value="8">
                      Content
                      8
                    </TabsContent>
                    <TabsContent value="9">
                      Content
                      9
                    </TabsContent>
                    <TabsContent value="10">
                      Content
                      10
                    </TabsContent>
                  </Tabs>
                </>
              ),
            )}
          </>
        ))}
      </>
    )
  }
